/* tslint:disable */
import {ActionModel} from './action-model';
import {ActiveStatusModel} from './active-status-model';
import {ApiErrorModel} from './api-error-model';
import {ApiSuccessModel} from './api-success-model';
import {AuthRequestModel} from './auth-request-model';
import {AuthResponseModel} from './auth-response-model';
import {CardModel} from './card-model';
import {ChatMessageModel} from './chat-message-model';
import {ClientMessageModel} from './client-message-model';
import {CurrentGameModel} from './current-game-model';
import {DeckModel} from './deck-model';
import {DrawGameDataContainerModel} from './draw-game-data-container-model';
import {DrawGameDrawModel} from './draw-game-draw-model';
import {GameActionModel} from './game-action-model';
import {GameListModel} from './game-list-model';
import {GameModel} from './game-model';
import {GameParameterModel} from './game-parameter-model';
import {GamePlayerModel} from './game-player-model';
import {GameSummaryModel} from './game-summary-model';
import {GenericServerMessage} from './generic-server-message';
import {HandActionModel} from './hand-action-model';
import {HandModel} from './hand-model';
import {HandSummaryModel} from './hand-summary-model';
import {JwtAuthRequestModel} from './jwt-auth-request-model';
import {LobbyModel} from './lobby-model';
import {LobbyPlayerModel} from './lobby-player-model';
import {NewAccountModel} from './new-account-model';
import {PlayerModel} from './player-model';
import {PokerTableModel} from './poker-table-model';
import {ToastClassModel} from './toast-class-model';
import {ToastModel} from './toast-model';
import {UserDocument} from './user-document';
import {UserModel} from './user-model';
import {WebSocketInfoModel} from './web-socket-info-model';
import {WebSocketUpdateModel} from './web-socket-update-model';

export interface ModelModel {
  actionModel?: ActionModel;
  activeStatusModel?: ActiveStatusModel;
  apiErrorModel?: ApiErrorModel;
  apiSuccessModel?: ApiSuccessModel;
  authRequestModel?: AuthRequestModel;
  authResponseModel?: AuthResponseModel;
  cardModel?: CardModel;
  cardSuit?: 'Spades' | 'Hearts' | 'Clubs' | 'Diamonds';
  cardValue?: 'Ace' | 'King' | 'Queen' | 'Jack' | 'Ten' | 'Nine' | 'Eight' | 'Seven' | 'Six' | 'Five' | 'Four' | 'Three' | 'Two';
  chatMessageModel?: ChatMessageModel;
  clientMessageModel?: ClientMessageModel;
  currentGameModel?: CurrentGameModel;
  deckModel?: DeckModel;
  drawGameDataContainerModel?: DrawGameDataContainerModel;
  drawGameDrawModel?: DrawGameDrawModel;
  gameAction?: 'Fold' | 'Check' | 'Raise' | 'Call' | 'Bet' | 'ReRaise' | 'Ready' | 'Join' | 'LeaveLobby' | 'Start' | 'LeaveGame' | 'ReJoinGame';
  gameActionModel?: GameActionModel;
  gameListModel?: GameListModel;
  gameModel?: GameModel;
  gameParameterModel?: GameParameterModel;
  gamePhase?: 'Lobby' | 'Play' | 'Over';
  gamePlayerModel?: GamePlayerModel;
  gameSummaryModel?: GameSummaryModel;
  genericServerMessage?: GenericServerMessage;
  handAction?: 'Start' | 'Roll' | 'Draw';
  handActionModel?: HandActionModel;
  handModel?: HandModel;
  handSummaryModel?: HandSummaryModel;
  jwtAuthRequestModel?: JwtAuthRequestModel;
  lobbyModel?: LobbyModel;
  lobbyPlayerModel?: LobbyPlayerModel;
  messageType?: 'GameList' | 'Lobby' | 'Game' | 'Hand' | 'GameData' | 'PlayerData' | 'Toast' | 'ReadyToggled' | 'PlayerJoinedLobby' | 'PlayerLeftLobby' | 'GamePhaseChanged' | 'HandStarted' | 'PlayerAwayToggled' | 'HandActionPerformed' | 'ActingPlayerChanged' | 'GamePlayer' | 'CardDrawnByPlayer' | 'StartTurnTimer' | 'PokerTable';
  newAccountModel?: NewAccountModel;
  playerModel?: PlayerModel;
  pokerTableModel?: PokerTableModel;
  toastClassModel?: ToastClassModel;
  toastModel?: ToastModel;
  userDocument?: UserDocument;
  userGroup?: 'Administrator' | 'Client' | 'Guest';
  userModel?: UserModel;
  webSocketInfoModel?: WebSocketInfoModel;
  webSocketUpdateModel?: WebSocketUpdateModel;
}
