name: Client Test and Build

on:
  push:
    paths:
      - 'poker-client**'
      - '.github/workflows/node.yml'

jobs:
  test-and-build-client:
    runs-on: ubuntu-latest
    env:
      working-directory: ./poker-client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
      - name: Run Unit Tests
        run: npm run test
        working-directory: ${{env.working-directory}}
      - name: Build
        run: npm run build
        working-directory: ${{env.working-directory}}
