name: Client S3 Deployment

on:
  push:
    branches:
      - develop
      - refactor-to-use-store

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      working-directory: ./poker-client
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
        working-directory: ${{env.working-directory}}
#      - name: Run Unit Tests
#       run: npm run test
#       working-directory: ${{env.working-directory}}
      - name: Deploy to S3
        run: npm run deploy
        working-directory: ${{env.working-directory}}
