name: Google Formatter

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./poker-server
    steps:
      - uses: actions/checkout@v2 # v2 minimum required
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: axel-op/googlejavaformat-action@v2.0.0
