# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 3.6

#    - name: MongoDB in GitHub Actions
#      uses: supercharge/mongodb-github-action@1.3.0
#      with:
#        mongodb-version: default
#        mongodb-replica-set: default
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

