name: Java CI with Maven

on:
  pull_request:
    paths: 
      - 'poker-server**'
      - '.github/workflows/maven.yml'
  push:
    paths: 
      - 'poker-server**'
      - '.github/workflows/maven.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./poker-server

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
      
    - name: Start MongoDB As Docker
      uses: wbari/start-mongoDB@v0.2
      with:
        mongoDBVersion: 3.6
    - name: Build with Maven
      run: mvn -B package --file pom.xml
