name: Java CI with Maven

on:
  push:
    paths:
      - 'poker-server**'
      - '.github/workflows/server-build-and-deploy.yml'
    branches:
      - 'develop'
  pull_request:
    paths:
      - 'poker-server**'
      - '.github/workflows/server-build-and-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    #    defaults:
    #      run:
    #        working-directory: ./poker-server

    steps:
      - uses: actions/checkout@v2

      # Setup JDK
      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      #    - name: Start MongoDB As Docker
      #      uses: wbari/start-mongoDB@v0.2
      #      with:
      #        mongoDBVersion: 3.6

      - name: Build
        working-directory: ./poker-server
        run: mvn -B package --file pom.xml

      # Setup NodeJS
      - name: Use Node 12.x
        #        if: github.event_name == 'push'
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      # Install npm Dependencies
      - name: Install npm Dependencies
        #        if: github.event_name == 'push'
        run: npm ci

      # Deploy Poker Server
      - name: Deploy Poker Server
        #        if: github.event_name == 'push'
        run: npm deploy
